"""
Generates pareto_mappo.ipynb and m2llm_ddpg.ipynb in the same directory.
Run once; delete this script afterwards.
"""

import json, os

DIR = os.path.dirname(os.path.abspath(__file__))


def nb(cells):
    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10.12"},
            "kaggle": {
                "accelerator": "nvidiaTeslaT4",
                "dataSources": [{"sourceType": "datasetVersion", "sourceId": "uav-fix5",
                                 "datasetId": "uav-fix5", "datasetVersionNumber": 1}],
                "isInternetEnabled": False,
                "language": "python",
                "isGpuEnabled": True,
            },
        },
        "cells": cells,
    }


def code(src):
    return {"cell_type": "code", "metadata": {}, "source": src,
            "outputs": [], "execution_count": None}


def md(src):
    return {"cell_type": "markdown", "metadata": {}, "source": src}


# ═══════════════════════════════════════════════════════════════════════════════
#  NOTEBOOK 1 — Pareto Multi-Mode MAPPO
# ═══════════════════════════════════════════════════════════════════════════════

PARETO_CELLS = [

md(["# Pareto Multi-Mode MAPPO — Crop Disease UAV\n",
    "Comparative baseline adapted from: *LLM-Driven Pareto-Optimal Multi-Mode RL*.\n\n",
    "Three specialized PPO policies (Aggressive / Balanced / Cautious) with mode-specific\n",
    "reward scaling. A hard-coded telemetry threshold selector (standing in for the paper's\n",
    "LLM selector) chooses a mode at the start of each episode from disease pressure,\n",
    "weather risk, and fleet battery context.\n",
    "All policies share one centralized critic with per-UAV heads.\n",
    "Environment: `uav_env_5` (identical disease dynamics to the main MAPPO baseline)."]),

code(["import os, sys\n",
      "ON_KAGGLE = os.path.exists('/kaggle/input')\n",
      "if ON_KAGGLE:\n",
      "    MODULE_DIR = '/kaggle/input/uav-fix5'\n",
      "    sys.path.insert(0, MODULE_DIR)\n",
      "else:\n",
      "    MODULE_DIR = os.path.join(os.path.dirname(os.getcwd()), 'fixes-2')\n",
      "    sys.path.insert(0, MODULE_DIR)\n",
      "print('Module dir:', MODULE_DIR)"]),

code(["import math, random, time, copy\n",
      "import numpy as np\n",
      "import torch\n",
      "import torch.nn as nn\n",
      "from torch.optim import Adam\n",
      "from torch.distributions import Normal\n",
      "import matplotlib.pyplot as plt\n",
      "\n",
      "from uav_env_5 import (\n",
      "    UAVFieldEnv,\n",
      "    N_UAVS, N_SECTORS, OBS_SIZE, JOINT_SIZE,\n",
      "    ENV_OBS_DIM, GRID_ROWS, GRID_COLS, N_SECTORS as NS,\n",
      ")\n",
      "from uav_env_5 import N_SECTORS\n",
      "\n",
      "DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
      "print('Device:', DEVICE)"]),

md(["## Mode Definitions\n",
    "Reward scaling factors per mode and a hard-coded selector that simulates the LLM\n",
    "mode-selection output using available crop-disease telemetry.\n\n",
    "| Mode       | detection | task_completion | safety |\n",
    "|------------|-----------|-----------------|--------|\n",
    "| Aggressive | 3.0       | 2.0             | 0.5    |\n",
    "| Balanced   | 1.5       | 1.0             | 1.0    |\n",
    "| Cautious   | 0.5       | 0.5             | 2.0    |"]),

code(["MODES = {\n",
      "    'aggressive': {'detection': 3.0, 'task': 2.0, 'safety': 0.5},\n",
      "    'balanced':   {'detection': 1.5, 'task': 1.0, 'safety': 1.0},\n",
      "    'cautious':   {'detection': 0.5, 'task': 0.5, 'safety': 2.0},\n",
      "}\n",
      "MODE_NAMES = list(MODES.keys())\n",
      "\n",
      "\n",
      "def build_selector_context(env):\n",
      "    \"\"\"Telemetry context used by the hard-coded LLM selector analogue.\"\"\"\n",
      "    infected_frac = float(env.true_status.sum()) / N_SECTORS\n",
      "    avg_energy = float(np.mean(env.energy)) / 150.0\n",
      "    weather_risk = max(\n",
      "        float(env.wind_speed) / 12.0,\n",
      "        float(env.humidity) / 100.0,\n",
      "        float(env.season_mult) / 1.5,\n",
      "    )\n",
      "    return {\n",
      "        'infected_frac': infected_frac,\n",
      "        'avg_energy': avg_energy,\n",
      "        'wind_speed': float(env.wind_speed),\n",
      "        'humidity': float(env.humidity),\n",
      "        'season_mult': float(env.season_mult),\n",
      "        'weather_risk': weather_risk,\n",
      "    }\n",
      "\n",
      "\n",
      "def select_mode(context: dict) -> str:\n",
      "    \"\"\"Hard-coded threshold selector used in place of a fine-tuned LLM.\"\"\"\n",
      "    # Safety first under low battery or turbulent wind.\n",
      "    if context['avg_energy'] < 0.35 or context['wind_speed'] >= 8.5:\n",
      "        return 'cautious'\n",
      "    # Escalate containment when disease pressure or weather-driven spread risk is high.\n",
      "    if (context['infected_frac'] >= 0.03 or\n",
      "            context['humidity'] >= 75.0 or\n",
      "            context['season_mult'] >= 1.15):\n",
      "        return 'aggressive'\n",
      "    # Use a middle policy for moderate environmental risk.\n",
      "    if context['weather_risk'] >= 0.55:\n",
      "        return 'balanced'\n",
      "    return 'cautious'\n",
      "\n",
      "\n",
      "def scale_reward(raw_reward: float, comp: dict, mode_params: dict) -> float:\n",
      "    \"\"\"Replace default component weights with mode-specific scaling.\"\"\"\n",
      "    r = raw_reward\n",
      "    # Swap discovery_bonus weight\n",
      "    r -= comp.get('discovery_bonus', 0.0)\n",
      "    r += mode_params['detection'] * comp.get('discovery_bonus', 0.0)\n",
      "    # Swap crash_penalty weight (was subtracted in env)\n",
      "    r += comp.get('crash_penalty', 0.0)\n",
      "    r -= mode_params['safety'] * comp.get('crash_penalty', 0.0)\n",
      "    # Swap safe_return_bonus weight\n",
      "    r -= comp.get('safe_return_bonus', 0.0)\n",
      "    r += mode_params['task'] * comp.get('safe_return_bonus', 0.0)\n",
      "    return r"]),

md(["## Network Architectures\n",
    "Imported from `networks_5.py` — identical to the main MAPPO baseline.\n",
    "- `SectorAttentionActor`: 2-layer Transformer over 100 sector tokens + global embed.\n",
    "- `CriticNetwork`: shared trunk + 4 per-UAV linear heads (one value head per UAV)."]),

code(["from networks_5 import SectorAttentionActor, CriticNetwork\n",
      "\n",
      "# One actor per mode; all share a single centralized critic\n",
      "actors     = {m: SectorAttentionActor().to(DEVICE) for m in MODE_NAMES}\n",
      "critic     = CriticNetwork().to(DEVICE)\n",
      "actor_opts = {m: Adam(actors[m].parameters(), lr=3e-4) for m in MODE_NAMES}\n",
      "critic_opt = Adam(critic.parameters(), lr=1e-3)\n",
      "print({m: sum(p.numel() for p in actors[m].parameters()) for m in MODE_NAMES})\n",
      "print('Critic params:', sum(p.numel() for p in critic.parameters()))"]),

md(["## Hyperparameters"]),

code(["EPISODES     = 400\n",
      "GAMMA_PPO    = 0.99\n",
      "GAE_LAMBDA   = 0.95\n",
      "K_EPOCHS     = 2\n",
      "MINI_BATCH   = 128\n",
      "CLIP_EPS     = 0.2\n",
      "MAX_GRAD     = 0.5\n",
      "REWARD_CLIP  = 50.0\n",
      "KL_THRESH    = 0.02\n",
      "ENTROPY_START = 0.01\n",
      "ENTROPY_END   = 0.001\n",
      "\n",
      "def entropy_coeff(ep):\n",
      "    t = ep / max(EPISODES - 1, 1)\n",
      "    return ENTROPY_START * (1 - t) + ENTROPY_END * t"]),

md(["## Rollout Buffer & GAE"]),

code(["class RolloutBuffer:\n",
      "    def __init__(self):\n",
      "        self.obs        = [[] for _ in range(N_UAVS)]\n",
      "        self.actions    = [[] for _ in range(N_UAVS)]\n",
      "        self.log_probs  = [[] for _ in range(N_UAVS)]\n",
      "        self.rewards    = [[] for _ in range(N_UAVS)]\n",
      "        self.values     = []\n",
      "        self.dones      = []\n",
      "        self.alive      = [[] for _ in range(N_UAVS)]\n",
      "\n",
      "    def clear(self):\n",
      "        self.__init__()\n",
      "\n",
      "\n",
      "def compute_gae(rewards_u, values_tensor, dones, alive_u):\n",
      "    T = len(rewards_u)\n",
      "    adv = torch.zeros(T, device=DEVICE)\n",
      "    gae = 0.0\n",
      "    vals = values_tensor.detach()\n",
      "    for t in reversed(range(T)):\n",
      "        mask  = 1.0 - float(dones[t])\n",
      "        next_v = vals[t + 1] if t + 1 < len(vals) else 0.0\n",
      "        delta = rewards_u[t] + GAMMA_PPO * next_v * mask - vals[t]\n",
      "        gae   = delta + GAMMA_PPO * GAE_LAMBDA * mask * gae\n",
      "        adv[t] = gae\n",
      "    ret = adv + vals[:T]\n",
      "    alive_t = torch.tensor(alive_u, dtype=torch.float32, device=DEVICE)\n",
      "    if alive_t.sum() > 1:\n",
      "        adv = (adv - adv[alive_t.bool()].mean()) / (adv[alive_t.bool()].std() + 1e-8)\n",
      "    return adv, ret"]),

code(["def ppo_update(mode, buf, ep):\n",
      "    actor = actors[mode]\n",
      "    a_opt = actor_opts[mode]\n",
      "    ent_c = entropy_coeff(ep)\n",
      "\n",
      "    T = len(buf.dones)\n",
      "    all_rews = np.concatenate([buf.rewards[u] for u in range(N_UAVS)])\n",
      "    scale    = max(float(np.std(all_rews)), 1.0)\n",
      "\n",
      "    joint_obs_t = torch.tensor(\n",
      "        np.stack([np.concatenate([buf.obs[u][t] for u in range(N_UAVS)])\n",
      "                  for t in range(T)]),\n",
      "        dtype=torch.float32, device=DEVICE)\n",
      "    with torch.no_grad():\n",
      "        all_vals = critic(joint_obs_t)  # (T, N_UAVS)\n",
      "\n",
      "    adv_list, ret_list = [], []\n",
      "    for u in range(N_UAVS):\n",
      "        rews_norm = [float(np.clip(r, -REWARD_CLIP, REWARD_CLIP)) / scale\n",
      "                     for r in buf.rewards[u]]\n",
      "        adv_u, ret_u = compute_gae(\n",
      "            rews_norm, all_vals[:, u], buf.dones, buf.alive[u])\n",
      "        adv_list.append(adv_u)\n",
      "        ret_list.append(ret_u)\n",
      "\n",
      "    obs_t    = [torch.tensor(np.array(buf.obs[u]),     dtype=torch.float32, device=DEVICE)\n",
      "                for u in range(N_UAVS)]\n",
      "    act_t    = [torch.tensor(np.array(buf.actions[u]), dtype=torch.float32, device=DEVICE)\n",
      "                for u in range(N_UAVS)]\n",
      "    lp_old_t = [torch.tensor(np.array(buf.log_probs[u]), dtype=torch.float32, device=DEVICE)\n",
      "                for u in range(N_UAVS)]\n",
      "    alive_t  = [torch.tensor(buf.alive[u], dtype=torch.float32, device=DEVICE)\n",
      "                for u in range(N_UAVS)]\n",
      "\n",
      "    idx = np.arange(T)\n",
      "    for _ in range(K_EPOCHS):\n",
      "        np.random.shuffle(idx)\n",
      "        for start in range(0, T, MINI_BATCH):\n",
      "            mb = idx[start:start + MINI_BATCH]\n",
      "            mb_t = torch.tensor(mb, device=DEVICE)\n",
      "\n",
      "            # Actor loss (mode-specific actor only)\n",
      "            a_loss = torch.tensor(0.0, device=DEVICE)\n",
      "            kl_sum = 0.0\n",
      "            for u in range(N_UAVS):\n",
      "                lp_new, ent = actor.get_log_prob_entropy(\n",
      "                    obs_t[u][mb_t], act_t[u][mb_t])\n",
      "                ratio  = torch.exp(lp_new - lp_old_t[u][mb_t])\n",
      "                adv_mb = adv_list[u][mb_t]\n",
      "                surr1  = ratio * adv_mb\n",
      "                surr2  = torch.clamp(ratio, 1 - CLIP_EPS, 1 + CLIP_EPS) * adv_mb\n",
      "                mb_alive = alive_t[u][mb_t]\n",
      "                pol_loss = (-torch.min(surr1, surr2) * mb_alive).sum()\n",
      "                n_alive  = mb_alive.sum().clamp(min=1)\n",
      "                a_loss  += pol_loss / n_alive - ent_c * ent\n",
      "                with torch.no_grad():\n",
      "                    kl_sum += (lp_old_t[u][mb_t] - lp_new).mean().item()\n",
      "\n",
      "            if kl_sum / N_UAVS > KL_THRESH:\n",
      "                break\n",
      "\n",
      "            a_opt.zero_grad()\n",
      "            (a_loss / N_UAVS).backward()\n",
      "            nn.utils.clip_grad_norm_(actor.parameters(), MAX_GRAD)\n",
      "            a_opt.step()\n",
      "\n",
      "            # Critic loss (shared)\n",
      "            pred_v = critic(joint_obs_t[mb_t])  # (mb, N_UAVS)\n",
      "            c_loss = sum(\n",
      "                nn.functional.mse_loss(pred_v[:, u], ret_list[u][mb_t])\n",
      "                for u in range(N_UAVS)\n",
      "            ) / N_UAVS\n",
      "            critic_opt.zero_grad()\n",
      "            c_loss.backward()\n",
      "            nn.utils.clip_grad_norm_(critic.parameters(), MAX_GRAD)\n",
      "            critic_opt.step()"]),

md(["## Training Loop"]),

code(["env = UAVFieldEnv(seed=42)\n",
      "\n",
      "ep_rewards   = []\n",
      "ep_infected  = []  # infected fraction at end of episode\n",
      "ep_diagnosed = []  # fraction of sectors ever diagnosed\n",
      "ep_crashes   = []\n",
      "ep_modes     = []\n",
      "ep_contexts  = []\n",
      "mode_counts  = {m: 0 for m in MODE_NAMES}\n",
      "\n",
      "t0 = time.time()\n",
      "for ep in range(EPISODES):\n",
      "    obs_list = env.reset()\n",
      "\n",
      "    # Mode selection: hard-coded telemetry thresholds simulating the LLM selector\n",
      "    selector_ctx  = build_selector_context(env)\n",
      "    mode          = select_mode(selector_ctx)\n",
      "    mode_params   = MODES[mode]\n",
      "    actor         = actors[mode]\n",
      "    mode_counts[mode] += 1\n",
      "    ep_modes.append(mode)\n",
      "    ep_contexts.append(selector_ctx)\n",
      "\n",
      "    buf = RolloutBuffer()\n",
      "    ep_r = 0.0\n",
      "    crashes_this_ep = 0\n",
      "\n",
      "    for _ in range(env.total_steps):\n",
      "        obs_tensors = [torch.tensor(obs_list[u], dtype=torch.float32, device=DEVICE)\n",
      "                       for u in range(N_UAVS)]\n",
      "\n",
      "        actions_np = []\n",
      "        log_probs  = []\n",
      "        for u in range(N_UAVS):\n",
      "            if env.crashed[u]:\n",
      "                actions_np.append(np.zeros(2, dtype=np.float32))\n",
      "                log_probs.append(torch.tensor(0.0, device=DEVICE))\n",
      "            else:\n",
      "                act, lp = actor.get_action(obs_tensors[u])\n",
      "                actions_np.append(act)\n",
      "                log_probs.append(lp.squeeze())\n",
      "\n",
      "        next_obs, raw_rewards, done, info = env.step(actions_np)\n",
      "\n",
      "        # Mode-specific reward scaling\n",
      "        comps = info['reward_components']\n",
      "        rewards = [scale_reward(raw_rewards[u], comps[u], mode_params)\n",
      "                   for u in range(N_UAVS)]\n",
      "\n",
      "        joint_obs_np = np.concatenate(obs_list)\n",
      "        for u in range(N_UAVS):\n",
      "            buf.obs[u].append(obs_list[u])\n",
      "            buf.actions[u].append(actions_np[u])\n",
      "            buf.log_probs[u].append(log_probs[u].item())\n",
      "            buf.rewards[u].append(rewards[u])\n",
      "            buf.alive[u].append(0.0 if env.crashed[u] else 1.0)\n",
      "        buf.dones.append(done)\n",
      "\n",
      "        ep_r += sum(raw_rewards)\n",
      "        crashes_this_ep += sum(info['newly_crashed'])\n",
      "        obs_list = next_obs\n",
      "        if done:\n",
      "            break\n",
      "\n",
      "    ppo_update(mode, buf, ep)\n",
      "\n",
      "    ep_rewards.append(ep_r)\n",
      "    ep_infected.append(float(env.true_status.sum()) / N_SECTORS)\n",
      "    ep_diagnosed.append(float(env.ever_diagnosed.sum()) / N_SECTORS)\n",
      "    ep_crashes.append(crashes_this_ep)\n",
      "\n",
      "    if (ep + 1) % 50 == 0:\n",
      "        elapsed = time.time() - t0\n",
      "        print(f'Ep {ep+1:4d}/{EPISODES} | mode={mode:10s} | '\n",
      "              f'reward={ep_r:8.1f} | inf={ep_infected[-1]:.2f} '\n",
      "              f'diag={ep_diagnosed[-1]:.2f} | crashes={crashes_this_ep} '\n",
      "              f'| {elapsed:.0f}s')\n",
      "\n",
      "print('\\nMode selection counts:', mode_counts)"]),

md(["## Metrics & Plots"]),

code(["fig, axes = plt.subplots(2, 2, figsize=(14, 8))\n",
      "fig.suptitle('Pareto Multi-Mode MAPPO — Training Curves', fontsize=14)\n",
      "\n",
      "def smooth(x, w=20):\n",
      "    return np.convolve(x, np.ones(w)/w, mode='valid')\n",
      "\n",
      "axes[0,0].plot(smooth(ep_rewards), label='smoothed')\n",
      "axes[0,0].set_title('Episode Reward'); axes[0,0].set_xlabel('Episode')\n",
      "\n",
      "axes[0,1].plot(smooth(ep_infected), color='red', label='smoothed')\n",
      "axes[0,1].set_title('Disease Fraction at End of Episode')\n",
      "axes[0,1].axhline(0.35, color='gray', linestyle='--', label='endemic baseline')\n",
      "axes[0,1].legend()\n",
      "\n",
      "axes[1,0].plot(smooth(ep_diagnosed), color='green')\n",
      "axes[1,0].set_title('Diagnosed Fraction per Episode')\n",
      "\n",
      "axes[1,1].plot(smooth(ep_crashes), color='orange')\n",
      "axes[1,1].set_title('Crashes per Episode')\n",
      "\n",
      "plt.tight_layout()\n",
      "plt.savefig('pareto_training.png', dpi=120, bbox_inches='tight')\n",
      "plt.show()\n",
      "print('Saved pareto_training.png')"]),

code(["# Summary statistics (last 50 episodes)\n",
      "last = slice(-50, None)\n",
      "print('=== Pareto MAPPO — Final 50 Episodes ===')\n",
      "print(f'Mean reward       : {np.mean(ep_rewards[last]):.2f}')\n",
      "print(f'Mean disease frac : {np.mean(ep_infected[last]):.3f}')\n",
      "print(f'Mean diag frac    : {np.mean(ep_diagnosed[last]):.3f}')\n",
      "print(f'Mean crashes/ep   : {np.mean(ep_crashes[last]):.2f}')\n",
      "print(f'Mode distribution : {mode_counts}')"]),

code(["import os\n",
      "SAVE_DIR = '/kaggle/working' if ON_KAGGLE else '.'\n",
      "for m in MODE_NAMES:\n",
      "    path = os.path.join(SAVE_DIR, f'pareto_actor_{m}.pt')\n",
      "    torch.save(actors[m].state_dict(), path)\n",
      "    print('Saved', path)\n",
      "torch.save(critic.state_dict(), os.path.join(SAVE_DIR, 'pareto_critic.pt'))\n",
      "print('Saved pareto_critic.pt')"]),

]

# ═══════════════════════════════════════════════════════════════════════════════
#  NOTEBOOK 2 — M2LLM + Centralized DDPG
# ═══════════════════════════════════════════════════════════════════════════════

M2LLM_CELLS = [

md(["# M2LLM-Driven Centralized DDPG — Crop Disease UAV\n",
    "Comparative baseline adapted from: *Trajectory Design and Beamforming with M2LLM-Driven DRL*.\n\n",
    "**Architecture:**\n",
    "- `LLMEncoder`: deep MLP with LayerNorm + GELU — simulates LLaVA hidden-layer projection.\n",
    "- `CentralDDPGActor`: single agent controlling all 4 UAVs jointly (12-dim action).\n",
    "- `CentralDDPGCritic`: Q(joint_state, joint_action) with target networks + soft update.\n\n",
    "**Environment extension (`uav_env_beamforming.py`):**\n",
    "- Each UAV action: `[vx, vy, intensity]` — intensity maps beamforming resource allocation.\n",
    "- Higher intensity → faster treatment (fewer days), plus `tx_quality_bonus` in reward.\n",
    "- All disease dynamics identical to `uav_env_5`."]),

code(["import os, sys\n",
      "ON_KAGGLE = os.path.exists('/kaggle/input')\n",
      "if ON_KAGGLE:\n",
      "    MODULE_DIR = '/kaggle/input/uav-fix5'\n",
      "else:\n",
      "    # Notebook lives in new-implementation/; env + networks files are in the same dir\n",
      "    MODULE_DIR = os.getcwd()\n",
      "sys.path.insert(0, MODULE_DIR)\n",
      "print('Module dir:', MODULE_DIR)"]),

code(["import math, random, time, collections\n",
      "import numpy as np\n",
      "import torch\n",
      "import torch.nn as nn\n",
      "import torch.nn.functional as F\n",
      "from torch.optim import Adam\n",
      "import matplotlib.pyplot as plt\n",
      "\n",
      "from uav_env_beamforming import (\n",
      "    UAVFieldEnvBeamforming,\n",
      "    N_UAVS, N_SECTORS, OBS_SIZE, JOINT_SIZE,\n",
      "    ACTION_DIM, JOINT_ACTION_DIM,\n",
      ")\n",
      "\n",
      "DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
      "print('Device:', DEVICE, '| JOINT_SIZE:', JOINT_SIZE, '| JOINT_ACTION_DIM:', JOINT_ACTION_DIM)"]),

md(["## Network Architectures\n",
    "Imported from `networks_beamforming.py`.\n",
    "- `LLMEncoder`: 512→512→256 MLP with LayerNorm + GELU — simulates LLaVA hidden-layer projection.\n",
    "- `CentralDDPGActor`: joint_obs (880) → LLMEncoder → 128 → JOINT_ACTION_DIM (12) → Tanh.\n",
    "- `CentralDDPGCritic`: obs_emb (256) + joint_action (12) → 256 → 128 → Q scalar."]),

code(["from networks_beamforming import LLMEncoder, CentralDDPGActor, CentralDDPGCritic\n",
      "\n",
      "actor         = CentralDDPGActor().to(DEVICE)\n",
      "critic        = CentralDDPGCritic().to(DEVICE)\n",
      "target_actor  = CentralDDPGActor().to(DEVICE)\n",
      "target_critic = CentralDDPGCritic().to(DEVICE)\n",
      "target_actor.load_state_dict(actor.state_dict())\n",
      "target_critic.load_state_dict(critic.state_dict())\n",
      "\n",
      "actor_opt  = Adam(actor.parameters(),  lr=1e-4)\n",
      "critic_opt = Adam(critic.parameters(), lr=1e-3)\n",
      "print('Actor  params:', sum(p.numel() for p in actor.parameters()))\n",
      "print('Critic params:', sum(p.numel() for p in critic.parameters()))"]),

md(["## Replay Buffer & OUNoise"]),

code(["class ReplayBuffer:\n",
      "    def __init__(self, capacity: int = 200_000):\n",
      "        self.buf = collections.deque(maxlen=capacity)\n",
      "\n",
      "    def push(self, s, a, r, s2, done):\n",
      "        self.buf.append((s, a, r, s2, done))\n",
      "\n",
      "    def sample(self, batch_size: int):\n",
      "        batch = random.sample(self.buf, batch_size)\n",
      "        s, a, r, s2, d = map(np.array, zip(*batch))\n",
      "        return (\n",
      "            torch.tensor(s,  dtype=torch.float32, device=DEVICE),\n",
      "            torch.tensor(a,  dtype=torch.float32, device=DEVICE),\n",
      "            torch.tensor(r,  dtype=torch.float32, device=DEVICE).unsqueeze(1),\n",
      "            torch.tensor(s2, dtype=torch.float32, device=DEVICE),\n",
      "            torch.tensor(d,  dtype=torch.float32, device=DEVICE).unsqueeze(1),\n",
      "        )\n",
      "\n",
      "    def __len__(self):\n",
      "        return len(self.buf)\n",
      "\n",
      "\n",
      "class OUNoise:\n",
      "    \"\"\"Ornstein-Uhlenbeck noise for DDPG exploration.\"\"\"\n",
      "    def __init__(self, dim: int, mu: float = 0.0, theta: float = 0.15,\n",
      "                 sigma: float = 0.2):\n",
      "        self.dim   = dim\n",
      "        self.mu    = mu\n",
      "        self.theta = theta\n",
      "        self.sigma = sigma\n",
      "        self.state = np.zeros(dim)\n",
      "\n",
      "    def reset(self):\n",
      "        self.state = np.zeros(self.dim)\n",
      "\n",
      "    def sample(self):\n",
      "        dx = self.theta * (self.mu - self.state) + self.sigma * np.random.randn(self.dim)\n",
      "        self.state += dx\n",
      "        return self.state.copy()"]),

md(["## Hyperparameters"]),

code(["EPISODES      = 400\n",
      "GAMMA_DDPG    = 0.99\n",
      "TAU_SOFT      = 0.005   # soft target update rate\n",
      "BATCH_SIZE    = 256\n",
      "WARMUP_STEPS  = 2000    # random actions before training\n",
      "REWARD_CLIP   = 50.0\n",
      "NOISE_DECAY   = 0.999   # multiply sigma each episode\n",
      "NOISE_MIN     = 0.05\n",
      "\n",
      "replay = ReplayBuffer()\n",
      "noise  = OUNoise(JOINT_ACTION_DIM)\n",
      "global_step = 0"]),

md(["## DDPG Update"]),

code(["def ddpg_update():\n",
      "    if len(replay) < BATCH_SIZE:\n",
      "        return None, None\n",
      "    s, a, r, s2, done = replay.sample(BATCH_SIZE)\n",
      "\n",
      "    # Critic update\n",
      "    with torch.no_grad():\n",
      "        a2     = target_actor(s2)\n",
      "        q_next = target_critic(s2, a2)\n",
      "        y      = torch.clamp(r, -REWARD_CLIP, REWARD_CLIP) + GAMMA_DDPG * q_next * (1 - done)\n",
      "    q_pred  = critic(s, a)\n",
      "    c_loss  = F.mse_loss(q_pred, y)\n",
      "    critic_opt.zero_grad()\n",
      "    c_loss.backward()\n",
      "    nn.utils.clip_grad_norm_(critic.parameters(), 1.0)\n",
      "    critic_opt.step()\n",
      "\n",
      "    # Actor update\n",
      "    a_pred = actor(s)\n",
      "    a_loss = -critic(s, a_pred).mean()\n",
      "    actor_opt.zero_grad()\n",
      "    a_loss.backward()\n",
      "    nn.utils.clip_grad_norm_(actor.parameters(), 1.0)\n",
      "    actor_opt.step()\n",
      "\n",
      "    # Soft target updates\n",
      "    for tp, p in zip(target_actor.parameters(),  actor.parameters()):\n",
      "        tp.data.mul_(1 - TAU_SOFT).add_(TAU_SOFT * p.data)\n",
      "    for tp, p in zip(target_critic.parameters(), critic.parameters()):\n",
      "        tp.data.mul_(1 - TAU_SOFT).add_(TAU_SOFT * p.data)\n",
      "\n",
      "    return c_loss.item(), a_loss.item()"]),

md(["## Training Loop"]),

code(["env = UAVFieldEnvBeamforming(seed=42)\n",
      "\n",
      "ep_rewards   = []\n",
      "ep_infected  = []\n",
      "ep_diagnosed = []\n",
      "ep_crashes   = []\n",
      "ep_c_losses  = []\n",
      "ep_a_losses  = []\n",
      "\n",
      "t0 = time.time()\n",
      "for ep in range(EPISODES):\n",
      "    obs_list   = env.reset()\n",
      "    joint_obs  = np.concatenate(obs_list).astype(np.float32)\n",
      "    noise.reset()\n",
      "    noise.sigma = max(noise.sigma * NOISE_DECAY, NOISE_MIN)\n",
      "\n",
      "    ep_r = 0.0\n",
      "    crashes_ep = 0\n",
      "    c_loss_ep, a_loss_ep = [], []\n",
      "\n",
      "    for _ in range(env.total_steps):\n",
      "        # Select action\n",
      "        if global_step < WARMUP_STEPS:\n",
      "            joint_action = np.random.uniform(-1, 1, JOINT_ACTION_DIM).astype(np.float32)\n",
      "        else:\n",
      "            with torch.no_grad():\n",
      "                obs_t = torch.tensor(joint_obs, dtype=torch.float32,\n",
      "                                     device=DEVICE).unsqueeze(0)\n",
      "                joint_action = actor(obs_t).squeeze(0).cpu().numpy()\n",
      "            joint_action = np.clip(joint_action + noise.sample(), -1.0, 1.0)\n",
      "\n",
      "        next_obs_list, rewards, done, info = env.step(joint_action)\n",
      "        next_joint_obs = np.concatenate(next_obs_list).astype(np.float32)\n",
      "\n",
      "        total_reward = float(sum(rewards))\n",
      "        replay.push(joint_obs, joint_action, total_reward, next_joint_obs, float(done))\n",
      "        global_step += 1\n",
      "\n",
      "        cl, al = ddpg_update()\n",
      "        if cl is not None:\n",
      "            c_loss_ep.append(cl)\n",
      "            a_loss_ep.append(al)\n",
      "\n",
      "        ep_r += total_reward\n",
      "        crashes_ep += sum(info['newly_crashed'])\n",
      "        joint_obs = next_joint_obs\n",
      "        if done:\n",
      "            break\n",
      "\n",
      "    ep_rewards.append(ep_r)\n",
      "    ep_infected.append(float(env.true_status.sum()) / N_SECTORS)\n",
      "    ep_diagnosed.append(float(env.ever_diagnosed.sum()) / N_SECTORS)\n",
      "    ep_crashes.append(crashes_ep)\n",
      "    ep_c_losses.append(np.mean(c_loss_ep) if c_loss_ep else float('nan'))\n",
      "    ep_a_losses.append(np.mean(a_loss_ep) if a_loss_ep else float('nan'))\n",
      "\n",
      "    if (ep + 1) % 50 == 0:\n",
      "        elapsed = time.time() - t0\n",
      "        print(f'Ep {ep+1:4d}/{EPISODES} | reward={ep_r:8.1f} '\n",
      "              f'| inf={ep_infected[-1]:.2f} diag={ep_diagnosed[-1]:.2f} '\n",
      "              f'| crashes={crashes_ep} | noise_sigma={noise.sigma:.3f} '\n",
      "              f'| {elapsed:.0f}s')"]),

md(["## Metrics & Plots"]),

code(["fig, axes = plt.subplots(2, 3, figsize=(18, 8))\n",
      "fig.suptitle('M2LLM-Driven Centralized DDPG — Training Curves', fontsize=14)\n",
      "\n",
      "def smooth(x, w=20):\n",
      "    return np.convolve(x, np.ones(w)/w, mode='valid')\n",
      "\n",
      "axes[0,0].plot(smooth(ep_rewards))\n",
      "axes[0,0].set_title('Episode Reward')\n",
      "\n",
      "axes[0,1].plot(smooth(ep_infected), color='red')\n",
      "axes[0,1].axhline(0.35, color='gray', linestyle='--', label='endemic baseline')\n",
      "axes[0,1].set_title('Disease Fraction at End')\n",
      "axes[0,1].legend()\n",
      "\n",
      "axes[0,2].plot(smooth(ep_diagnosed), color='green')\n",
      "axes[0,2].set_title('Diagnosed Fraction')\n",
      "\n",
      "axes[1,0].plot(smooth(ep_crashes), color='orange')\n",
      "axes[1,0].set_title('Crashes per Episode')\n",
      "\n",
      "valid_c = [x for x in ep_c_losses if not math.isnan(x)]\n",
      "axes[1,1].plot(smooth(valid_c), color='purple')\n",
      "axes[1,1].set_title('Critic Loss')\n",
      "\n",
      "valid_a = [x for x in ep_a_losses if not math.isnan(x)]\n",
      "axes[1,2].plot(smooth(valid_a), color='teal')\n",
      "axes[1,2].set_title('Actor Loss')\n",
      "\n",
      "plt.tight_layout()\n",
      "plt.savefig('m2llm_ddpg_training.png', dpi=120, bbox_inches='tight')\n",
      "plt.show()\n",
      "print('Saved m2llm_ddpg_training.png')"]),

code(["last = slice(-50, None)\n",
      "print('=== M2LLM DDPG — Final 50 Episodes ===')\n",
      "print(f'Mean reward       : {np.mean(ep_rewards[last]):.2f}')\n",
      "print(f'Mean disease frac : {np.mean(ep_infected[last]):.3f}')\n",
      "print(f'Mean diag frac    : {np.mean(ep_diagnosed[last]):.3f}')\n",
      "print(f'Mean crashes/ep   : {np.mean(ep_crashes[last]):.2f}')"]),

code(["SAVE_DIR = '/kaggle/working' if ON_KAGGLE else '.'\n",
      "torch.save(actor.state_dict(),         os.path.join(SAVE_DIR, 'm2llm_actor.pt'))\n",
      "torch.save(critic.state_dict(),        os.path.join(SAVE_DIR, 'm2llm_critic.pt'))\n",
      "torch.save(target_actor.state_dict(),  os.path.join(SAVE_DIR, 'm2llm_target_actor.pt'))\n",
      "torch.save(target_critic.state_dict(), os.path.join(SAVE_DIR, 'm2llm_target_critic.pt'))\n",
      "print('Saved m2llm actor/critic weights to', SAVE_DIR)"]),

]

# ─── Write notebooks ──────────────────────────────────────────────────────────

p1_path = os.path.join(DIR, 'pareto_mappo.ipynb')
p2_path = os.path.join(DIR, 'm2llm_ddpg.ipynb')

with open(p1_path, 'w') as f:
    json.dump(nb(PARETO_CELLS), f, indent=1)
print(f'Written {p1_path}  ({os.path.getsize(p1_path):,} bytes)')

with open(p2_path, 'w') as f:
    json.dump(nb(M2LLM_CELLS), f, indent=1)
print(f'Written {p2_path}  ({os.path.getsize(p2_path):,} bytes)')
